---
title: "Cours – Systèmes linéaires"
subtitle: "Chapitre 07"
author: "Said MAHARI"
date: last-modified
date-format: "D MMMM YYYY"
lang: fr
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    html-math-method: katex
    css: styles.css
filters:
  - custom-numbered-blocks.lua
---

**MPSI (1re année) — Chapitre 07.** Équations linéaires, systèmes linéaires, substitution, méthode de Cramer, inversion de matrice, opérations élémentaires sur les lignes, systèmes échelonnés, pivot de Gauss, systèmes homogènes.

Ce chapitre a été réalisé conformément au programme marocain de mathématiques de la filière MPSI.

# Systèmes linéaires {-}

L'algèbre linéaire est un outil essentiel pour toutes les branches des mathématiques, en particulier lorsqu'il s'agit de modéliser puis de résoudre numériquement des problèmes issus de divers domaines : sciences physiques ou mécaniques, sciences du vivant, chimie, économie, sciences de l'ingénieur… Les systèmes linéaires forment la base calculatoire de l'algèbre linéaire. Le but de ce chapitre est essentiellement pratique : il s'agit de **résoudre des systèmes linéaires**.

# Introduction aux systèmes d'équations linéaires

## Exemple : deux droites dans le plan

L'équation d'une droite dans le plan $(Oxy)$ s'écrit
$$ax+by=e$$
où $a$, $b$ et $e$ sont des paramètres réels, $a$ et $b$ n'étant pas simultanément nuls. Cette équation s'appelle **équation linéaire** dans les variables (ou inconnues) $x$ et $y$.

Par exemple, $2x+3y=6$ est une équation linéaire, alors que les équations suivantes ne sont pas des équations linéaires :
$$2x+y^2=1 \quad \text{ou} \quad y=\sin(x) \quad \text{ou} \quad x=\sqrt{y}.$$

Considérons maintenant deux droites $D_1$ et $D_2$ et cherchons les points qui sont simultanément sur ces deux droites. Un point $(x,y)$ est dans l'intersection $D_1\cap D_2$ s'il est solution du système :
$$(S)\qquad \begin{cases} ax+by &= e \\ cx+dy &= f \end{cases}$$

Trois cas se présentent alors :

1. Les droites $D_1$ et $D_2$ se coupent en un seul point : le système $(S)$ a une seule solution.
2. Les droites $D_1$ et $D_2$ sont parallèles : le système $(S)$ n'a pas de solution.
3. Les droites $D_1$ et $D_2$ sont confondues : le système $(S)$ a une infinité de solutions.

Nous verrons plus loin que ces trois cas de figure (une seule solution, aucune solution, une infinité de solutions) sont les seuls qui peuvent se présenter pour n'importe quel système d'équations linéaires.

## Résolution par substitution

Pour savoir s'il existe une ou plusieurs solutions à un système linéaire, et les calculer, une première méthode est la **substitution**. Par exemple pour le système :
$$(S)\qquad \begin{cases} 3x+2y &= 1 \\ 2x-7y &= -2 \end{cases}$$

Nous réécrivons la première ligne $3x+2y=1$ sous la forme $y=\frac12-\frac32 x$, et nous remplaçons (nous *substituons*) le $y$ de la seconde équation par l'expression $\frac12-\frac32 x$. Nous obtenons un système équivalent :
$$\begin{cases} y &= \frac12-\frac32 x \\ 2x-7\left(\frac12-\frac32 x\right) &= -2 \end{cases}$$

La seconde équation ne contient maintenant que des $x$, et on peut la résoudre :
$$\begin{cases} y &= \frac12-\frac32 x \\ \left(2+7\times\frac32\right)x &= -2+\frac72 \end{cases} \iff \begin{cases} y &= \frac12-\frac32 x \\ x &= \frac{3}{25} \end{cases}$$

Il ne reste plus qu'à remplacer dans la première ligne la valeur de $x$ obtenue :
$$\begin{cases} y &= \frac{8}{25} \\ x &= \frac{3}{25} \end{cases}$$

Le système $(S)$ admet donc une solution unique $\left(\frac{3}{25},\frac{8}{25}\right)$. L'ensemble des solutions est donc
$$\mathcal{S}=\left\{\left(\frac{3}{25},\frac{8}{25}\right)\right\}.$$

## Exemple : deux plans dans l'espace

Dans l'espace $(Oxyz)$, une équation linéaire est l'équation d'un plan :
$$ax+by+cz=d$$
(on suppose ici que $a$, $b$ et $c$ ne sont pas simultanément nuls). L'intersection de deux plans dans l'espace correspond au système suivant à $2$ équations et $3$ inconnues :
$$\begin{cases} ax+by+cz &= d \\ a'x+b'y+c'z &= d' \end{cases}$$

Trois cas se présentent alors :

- les plans sont parallèles (et distincts) et il n'y a alors aucune solution au système ;
- les plans sont confondus et il y a une infinité de solutions au système ;
- les plans se coupent en une droite et il y a une infinité de solutions.

::: {.example}

1. Le système $\begin{cases} 2x+3y-4z &= 7 \\ 4x+6y-8z &= -1 \end{cases}$ n'a pas de solution. En effet, en divisant par $2$ la seconde équation, on obtient le système équivalent $\begin{cases} 2x+3y-4z &= 7 \\ 2x+3y-4z &= -\frac12 \end{cases}$. Les deux lignes sont clairement incompatibles : aucun $(x,y,z)$ ne peut vérifier à la fois $2x+3y-4z=7$ et $2x+3y-4z=-\frac12$. L'ensemble des solutions est donc $\mathcal{S}=\varnothing$.
2. Pour le système $\begin{cases} 2x+3y-4z &= 7 \\ 4x+6y-8z &= 14 \end{cases}$, les deux équations définissent le même plan ! Le système est donc équivalent à une seule équation : $2x+3y-4z=7$. Si on réécrit cette équation sous la forme $z=\frac12 x+\frac34 y-\frac74$, alors on peut décrire l'ensemble des solutions sous la forme :
$$\mathcal{S}=\left\{(x,y,\tfrac12 x+\tfrac34 y-\tfrac74) \mid x,y\in\mathbb{R}\right\}.$$
3. Soit le système $\begin{cases} 7x+2y-2z &= 1 \\ 2x+3y+2z &= 1 \end{cases}$. Par substitution :
$$\begin{cases} 7x+2y-2z &= 1 \\ 2x+3y+2z &= 1 \end{cases} \iff \begin{cases} z &= \frac72 x+y-\frac12 \\ 9x+5y &= 2 \end{cases} \iff \begin{cases} z &= \frac{17}{10}x-\frac{1}{10} \\ y &= -\frac95 x+\frac25 \end{cases}$$
Pour décrire l'ensemble des solutions, on peut choisir $x$ comme paramètre :
$$\mathcal{S}=\left\{\left(x,\,-\tfrac95 x+\tfrac25,\,\tfrac{17}{10}x-\tfrac{1}{10}\right) \mid x\in\mathbb{R}\right\}.$$
Géométriquement : nous avons trouvé une équation paramétrique de la droite définie par l'intersection des deux plans.

:::

Du point de vue du nombre de solutions, nous constatons qu'il n'y a que deux possibilités : aucune solution ou une infinité de solutions. Mais les deux derniers cas ci-dessus sont néanmoins très différents géométriquement. Si on considère trois plans dans l'espace, une autre possibilité apparaît : il se peut que les trois plans s'intersectent en un seul point.

## Résolution par la méthode de Cramer

On note $\begin{vmatrix} a & b \\ c & d \end{vmatrix}=ad-bc$ le **déterminant**. On considère le cas d'un système de $2$ équations à $2$ inconnues :
$$\begin{cases} ax+by &= e \\ cx+dy &= f \end{cases}$$

Si $ad-bc\neq 0$, on trouve une unique solution dont les coordonnées $(x,y)$ sont :
$$x=\frac{\begin{vmatrix} e & b \\ f & d \end{vmatrix}}{\begin{vmatrix} a & b \\ c & d \end{vmatrix}} \qquad y=\frac{\begin{vmatrix} a & e \\ c & f \end{vmatrix}}{\begin{vmatrix} a & b \\ c & d \end{vmatrix}}$$

Notez que le dénominateur égale le déterminant pour les deux coordonnées et est donc non nul. Pour le numérateur de la première coordonnée $x$, on remplace la première colonne par le second membre ; pour la seconde coordonnée $y$, on remplace la seconde colonne par le second membre.

::: {.example}

Résolvons le système $\begin{cases} tx-2y &= 1 \\ 3x+ty &= 1 \end{cases}$ suivant la valeur du paramètre $t\in\mathbb{R}$.

Le déterminant associé au système est $\begin{vmatrix} t & -2 \\ 3 & t \end{vmatrix}=t^2+6$ et ne s'annule jamais. Il existe donc une unique solution $(x,y)$ et elle vérifie :
$$x=\frac{\begin{vmatrix} 1 & -2 \\ 1 & t \end{vmatrix}}{t^2+6}=\frac{t+2}{t^2+6}, \qquad y=\frac{\begin{vmatrix} t & 1 \\ 3 & 1 \end{vmatrix}}{t^2+6}=\frac{t-3}{t^2+6}.$$
Pour chaque $t$, l'ensemble des solutions est $\mathcal{S}=\left\{\left(\frac{t+2}{t^2+6},\frac{t-3}{t^2+6}\right)\right\}$.

:::

## Résolution par inversion de matrice

En termes matriciels, le système linéaire
$$\begin{cases} ax+by &= e \\ cx+dy &= f \end{cases}$$
est équivalent à
$$AX=Y \quad \text{où} \quad A=\begin{pmatrix} a & b \\ c & d \end{pmatrix}, \quad X=\begin{pmatrix} x \\ y \end{pmatrix}, \quad Y=\begin{pmatrix} e \\ f \end{pmatrix}.$$

Si le déterminant de la matrice $A$ est non nul, c'est-à-dire si $ad-bc\neq 0$, alors la matrice $A$ est inversible et
$$A^{-1}=\frac{1}{ad-bc}\begin{pmatrix} d & -b \\ -c & a \end{pmatrix}$$
et l'unique solution $X=\begin{pmatrix} x \\ y \end{pmatrix}$ du système est donnée par
$$X=A^{-1}Y.$$

::: {.example}

Résolvons le système $\begin{cases} x+y &= 1 \\ x+t^2y &= t \end{cases}$ suivant la valeur du paramètre $t\in\mathbb{R}$.

Le déterminant du système est $\begin{vmatrix} 1 & 1 \\ 1 & t^2 \end{vmatrix}=t^2-1$.

**Premier cas : $t\neq 1$ et $t\neq -1$.** Alors $t^2-1\neq 0$. La matrice $A=\begin{pmatrix} 1 & 1 \\ 1 & t^2 \end{pmatrix}$ est inversible d'inverse $A^{-1}=\frac{1}{t^2-1}\begin{pmatrix} t^2 & -1 \\ -1 & 1 \end{pmatrix}$. Et la solution $X=\begin{pmatrix} x \\ y \end{pmatrix}$ est
$$X=A^{-1}Y=\frac{1}{t^2-1}\begin{pmatrix} t^2 & -1 \\ -1 & 1 \end{pmatrix}\begin{pmatrix} 1 \\ t \end{pmatrix}=\frac{1}{t^2-1}\begin{pmatrix} t^2-t \\ t-1 \end{pmatrix}=\begin{pmatrix} \frac{t}{t+1} \\ \frac{1}{t+1} \end{pmatrix}.$$
Pour chaque $t\neq\pm 1$, l'ensemble des solutions est $\mathcal{S}=\left\{\left(\frac{t}{t+1},\frac{1}{t+1}\right)\right\}$.

**Deuxième cas : $t=1$.** Le système s'écrit alors $\begin{cases} x+y &= 1 \\ x+y &= 1 \end{cases}$ et les deux équations sont identiques. Il y a une infinité de solutions : $\mathcal{S}=\{(x,1-x) \mid x\in\mathbb{R}\}$.

**Troisième cas : $t=-1$.** Le système s'écrit $\begin{cases} x+y &= 1 \\ x+y &= -1 \end{cases}$ ; les deux équations sont clairement incompatibles et donc $\mathcal{S}=\varnothing$.

:::

::: {.exercise}

1. Tracer les droites d'équations $\begin{cases} x-2y &= -1 \\ -x+3y &= 3 \end{cases}$ et résoudre le système de trois façons différentes : substitution, méthode de Cramer, inverse d'une matrice. Idem avec $\begin{cases} 2x-y &= 4 \\ 3x+3y &= -5 \end{cases}$.
2. Résoudre suivant la valeur du paramètre $t\in\mathbb{R}$ : $\begin{cases} 4x-3y &= t \\ 2x-y &= t^2 \end{cases}$.
3. Discuter et résoudre suivant la valeur du paramètre $t\in\mathbb{R}$ : $\begin{cases} tx-y &= 1 \\ x+(t-2)y &= -1 \end{cases}$. Idem avec $\begin{cases} (t-1)x+y &= 1 \\ 2x+ty &= -1 \end{cases}$.

:::

# Théorie des systèmes linéaires

## Définitions

::: {.definition}

On appelle **équation linéaire** dans les variables (ou **inconnues**) $x_1,\ldots,x_p$ toute relation de la forme
$$a_1x_1+\cdots+a_px_p=b,$$
où $a_1,\ldots,a_p$ et $b$ sont des nombres réels donnés.

:::

::: {.remark}

- Il importe d'insister sur le fait que ces équations linéaires sont *implicites*, c'est-à-dire qu'elles décrivent des relations entre les variables, mais ne donnent pas directement les valeurs que peuvent prendre les variables.
- *Résoudre* une équation signifie donc la rendre *explicite*, c'est-à-dire rendre plus apparentes les valeurs que les variables peuvent prendre.
- On peut aussi considérer des équations linéaires de nombres rationnels ou de nombres complexes.

:::

Soit $n\geq 1$ un entier.

::: {.definition}

Un **système de $n$ équations linéaires à $p$ inconnues** est une liste de $n$ équations linéaires.

:::

On écrit usuellement de tels systèmes en $n$ lignes placées les unes sous les autres.

::: {.example}

Le système suivant a $2$ équations et $3$ inconnues :
$$\begin{cases} x_1-3x_2+x_3 &= 1 \\ -2x_1+4x_2-3x_3 &= 9 \end{cases}$$

:::

La forme générale d'un système linéaire de $n$ équations à $p$ inconnues est la suivante :
$$\begin{cases} a_{11}x_1+a_{12}x_2+a_{13}x_3+\cdots+a_{1p}x_p &= b_1 & (\leftarrow \text{équation } 1) \\ a_{21}x_1+a_{22}x_2+a_{23}x_3+\cdots+a_{2p}x_p &= b_2 & (\leftarrow \text{équation } 2) \\ \qquad\vdots \\ a_{i1}x_1+a_{i2}x_2+a_{i3}x_3+\cdots+a_{ip}x_p &= b_i & (\leftarrow \text{équation } i) \\ \qquad\vdots \\ a_{n1}x_1+a_{n2}x_2+a_{n3}x_3+\cdots+a_{np}x_p &= b_n & (\leftarrow \text{équation } n) \end{cases}$$

Les nombres $a_{ij}$, $i=1,\ldots,n$, $j=1,\ldots,p$, sont les **coefficients** du système. Ce sont des données. Les nombres $b_i$, $i=1,\ldots,n$, constituent le **second membre** du système et sont également des données. Il convient de bien observer comment on a rangé le système en lignes (une ligne par équation) numérotées de $1$ à $n$ par l'indice $i$, et en colonnes : les termes correspondant à une même inconnue $x_j$ sont alignés verticalement les uns sous les autres. L'indice $j$ varie de $1$ à $p$. La notation avec double indice $a_{ij}$ correspond à ce rangement : le premier indice (ici $i$) est le numéro de *ligne* et le second indice (ici $j$) est le numéro de *colonne*. Il est extrêmement important de toujours respecter cette convention.

Dans l'exemple précédent, on a $n=2$ (nombre d'équations = nombre de lignes), $p=3$ (nombre d'inconnues) et $a_{11}=1$, $a_{12}=-3$, $a_{13}=1$, $a_{21}=-2$, $a_{22}=4$, $a_{23}=-3$, $b_1=1$ et $b_2=9$.

::: {.definition}

Une **solution** du système linéaire est une liste de $p$ nombres réels $(s_1,s_2,\ldots,s_p)$ (un $p$-uplet) tels que, si l'on substitue $s_1$ pour $x_1$, $s_2$ pour $x_2$, etc., dans le système linéaire, on obtient une égalité. L'**ensemble des solutions du système** est l'ensemble de tous ces $p$-uplets.

:::

::: {.example}

Le système
$$\begin{cases} x_1-3x_2+x_3 &= 1 \\ -2x_1+4x_2-3x_3 &= 9 \end{cases}$$
admet comme solution $(-18,-6,1)$, c'est-à-dire
$$x_1=-18, \qquad x_2=-6, \qquad x_3=1.$$
Par contre, $(7,2,0)$ ne satisfait que la première équation. Ce n'est donc pas une solution du système.

:::

En règle générale, on s'attache à déterminer l'ensemble des solutions d'un système linéaire. C'est ce que l'on appelle **résoudre** le système linéaire. Ceci amène à poser la définition suivante.

::: {.definition}

On dit que deux systèmes linéaires sont **équivalents** s'ils ont le même ensemble de solutions.

:::

À partir de là, le jeu pour résoudre un système linéaire donné consistera à le transformer en un système équivalent dont la résolution sera plus simple que celle du système de départ. Nous verrons plus loin comment procéder de façon systématique pour arriver à ce but.

## Différents types de systèmes

Voici un résultat théorique important pour les systèmes linéaires.

::: {.theorem}

Un système d'équations linéaires n'a soit aucune solution, soit une seule solution, soit une infinité de solutions.

:::

En particulier, si vous trouvez $2$ solutions différentes à un système linéaire, alors c'est que vous pouvez en trouver une infinité ! Un système linéaire qui n'a aucune solution est dit **incompatible**. La preuve de ce théorème sera vue dans un chapitre ultérieur (« Matrices »).

## Systèmes homogènes

Un cas particulier important est celui des **systèmes homogènes**, pour lesquels $b_1=b_2=\cdots=b_n=0$, c'est-à-dire dont le second membre est nul. De tels systèmes sont toujours compatibles car ils admettent toujours la solution $s_1=s_2=\cdots=s_p=0$. Cette solution est appelée *solution triviale*. Géométriquement, dans le cas $2\times 2$, un système homogène correspond à deux droites qui passent par l'origine, $(0,0)$ étant donc toujours solution.

::: {.exercise}

1. Écrire un système linéaire de $4$ équations et $3$ inconnues qui n'a aucune solution. Idem avec une infinité de solutions. Idem avec une solution unique.
2. Résoudre le système à $n$ équations et $n$ inconnues dont les équations sont $(L_i)$ : $x_i-x_{i+1}=1$ pour $i=1,\ldots,n-1$ et $(L_n)$ : $x_n=1$.
3. Résoudre les systèmes suivants :
$$\begin{cases} x_1+2x_2+3x_3+4x_4 &= 0 \\ x_2+2x_3+3x_4 &= 9 \\ x_3+2x_4 &= 0 \end{cases} \quad \begin{cases} x_1+2x_2+3x_3 &= 1 \\ x_1+x_2+x_3 &= 2 \\ x_1-x_2+x_3 &= 3 \end{cases} \quad \begin{cases} x_1+x_2 &= 1 \\ x_2+x_3 &= 2 \\ x_3+x_4 &= 3 \\ x_1+2x_2+2x_3+x_4 &= 0 \end{cases}$$
4. Montrer que si un système linéaire *homogène* a une solution $(x_1,\ldots,x_p)\neq(0,\ldots,0)$, alors il admet une infinité de solutions.

:::

# Résolution par la méthode du pivot de Gauss

## Systèmes échelonnés

::: {.definition}

Un système est **échelonné** si :

- le nombre de coefficients nuls commençant une ligne croît strictement ligne après ligne.

Il est **échelonné réduit** si en plus :

- le premier coefficient non nul d'une ligne vaut $1$ ;
- et c'est le seul élément non nul de sa colonne.

:::

::: {.example}

- $\begin{cases} 2x_1+3x_2+2x_3-x_4 &= 5 \\ -x_2-2x_3 &= 4 \\ 3x_4 &= 1 \end{cases}$ est échelonné (mais pas réduit).
- $\begin{cases} 2x_1+3x_2+2x_3-x_4 &= 5 \\ -2x_3 &= 4 \\ x_3+x_4 &= 1 \end{cases}$ n'est pas échelonné (la dernière ligne commence avec la même variable que la ligne au-dessus).

:::

Il se trouve que les systèmes linéaires sous une forme échelonnée réduite sont particulièrement simples à résoudre.

::: {.example}

Le système linéaire suivant à $3$ équations et $4$ inconnues est échelonné et réduit :
$$\begin{cases} x_1+2x_3 &= 25 \\ x_2-2x_3 &= 16 \\ x_4 &= 1 \end{cases}$$
Ce système se résout trivialement en
$$\begin{cases} x_1 &= 25-2x_3 \\ x_2 &= 16+2x_3 \\ x_4 &= 1 \end{cases}$$
En d'autres termes, pour toute valeur de $x_3$ réelle, les valeurs de $x_1$, $x_2$ et $x_4$ calculées ci-dessus fournissent une solution du système, et on les a ainsi toutes obtenues. On peut donc décrire entièrement l'ensemble des solutions :
$$\mathcal{S}=\{(25-2x_3,\,16+2x_3,\,x_3,\,1) \mid x_3\in\mathbb{R}\}.$$

:::

## Opérations sur les équations d'un système

Nous allons utiliser trois opérations élémentaires sur les équations (c'est-à-dire sur les lignes) qui sont :

1. $L_i \leftarrow \lambda L_i$ avec $\lambda\neq 0$ : on peut multiplier une équation par un réel non nul.
2. $L_i \leftarrow L_i+\lambda L_j$ avec $\lambda\in\mathbb{R}$ (et $j\neq i$) : on peut ajouter à l'équation $L_i$ un multiple d'une autre équation $L_j$.
3. $L_i \leftrightarrow L_j$ : on peut échanger deux équations.

Ces trois opérations élémentaires ne changent pas les solutions d'un système linéaire ; autrement dit ces opérations transforment un système linéaire en un système linéaire équivalent.

::: {.example}

Utilisons ces opérations élémentaires pour résoudre le système suivant :
$$\begin{cases} x+y+7z &= -1 \\ 2x-y+5z &= -5 \\ -x-3y-9z &= -5 \end{cases}$$

Commençons par l'opération $L_2 \leftarrow L_2-2L_1$ : on soustrait à la deuxième équation deux fois la première équation. On obtient un système équivalent avec une nouvelle deuxième ligne (plus simple) :
$$\begin{cases} x+y+7z &= -1 \\ -3y-9z &= -3 & (L_2 \leftarrow L_2-2L_1) \\ -x-3y-9z &= -5 \end{cases}$$

Puis $L_3 \leftarrow L_3+L_1$ :
$$\begin{cases} x+y+7z &= -1 \\ -3y-9z &= -3 \\ -2y-2z &= -6 & (L_3 \leftarrow L_3+L_1) \end{cases}$$

On continue pour faire apparaître un coefficient $1$ en tête de la deuxième ligne ; pour cela on divise la ligne $L_2$ par $-3$ :
$$\begin{cases} x+y+7z &= -1 \\ y+3z &= 1 & (L_2 \leftarrow -\tfrac13 L_2) \\ -2y-2z &= -6 \end{cases}$$

On continue ainsi :
$$\begin{cases} x+y+7z &= -1 \\ y+3z &= 1 \\ 4z &= -4 & (L_3 \leftarrow L_3+2L_2) \end{cases} \qquad \begin{cases} x+y+7z &= -1 \\ y+3z &= 1 \\ z &= -1 & (L_3 \leftarrow \tfrac14 L_3) \end{cases}$$

$$\begin{cases} x+y+7z &= -1 \\ y &= 4 & (L_2 \leftarrow L_2-3L_3) \\ z &= -1 \end{cases} \qquad \begin{cases} x+y &= 6 & (L_1 \leftarrow L_1-7L_3) \\ y &= 4 \\ z &= -1 \end{cases}$$

On aboutit à un système réduit et échelonné :
$$\begin{cases} x &= 2 & (L_1 \leftarrow L_1-L_2) \\ y &= 4 \\ z &= -1 \end{cases}$$

On obtient ainsi $x=2$, $y=4$ et $z=-1$ et l'unique solution du système est $(2,4,-1)$.

:::

La méthode utilisée pour cet exemple est reprise et généralisée dans le paragraphe suivant.

## Méthode du pivot de Gauss

La méthode du pivot de Gauss permet de trouver les solutions de n'importe quel système linéaire. Nous allons décrire cet algorithme sur un exemple. Il s'agit d'une description précise d'une suite d'opérations à effectuer, qui dépendent de la situation et d'un ordre précis. Ce processus aboutit toujours (et en plus assez rapidement) à un système échelonné puis réduit, qui conduit immédiatement aux solutions du système.

**Partie A. Passage à une forme échelonnée.** Soit le système suivant à résoudre :
$$\begin{cases} -x_2+2x_3+13x_4 &= 5 \\ x_1-2x_2+3x_3+17x_4 &= 4 \\ -x_1+3x_2-3x_3-20x_4 &= -1 \end{cases}$$

Pour appliquer la méthode du pivot de Gauss, il faut d'abord que le premier coefficient de la première ligne soit non nul. Comme ce n'est pas le cas ici, on échange les deux premières lignes par l'opération élémentaire $L_1 \leftrightarrow L_2$ :
$$\begin{cases} x_1-2x_2+3x_3+17x_4 &= 4 & (L_1 \leftrightarrow L_2) \\ -x_2+2x_3+13x_4 &= 5 \\ -x_1+3x_2-3x_3-20x_4 &= -1 \end{cases}$$

Nous avons déjà un coefficient $1$ devant le $x_1$ de la première ligne. On dit que nous avons un **pivot** en position $(1,1)$ (première ligne, première colonne). Ce pivot sert de base pour éliminer tous les autres termes sur la même colonne. Il n'y a pas de terme $x_1$ sur la deuxième ligne. Faisons disparaître le terme $x_1$ de la troisième ligne ; pour cela on fait l'opération élémentaire $L_3 \leftarrow L_3+L_1$ :
$$\begin{cases} x_1-2x_2+3x_3+17x_4 &= 4 \\ -x_2+2x_3+13x_4 &= 5 \\ x_2-3x_4 &= 3 & (L_3 \leftarrow L_3+L_1) \end{cases}$$

On change le signe de la seconde ligne ($L_2 \leftarrow -L_2$) pour faire apparaître $1$ au coefficient du pivot $(2,2)$ (deuxième ligne, deuxième colonne) :
$$\begin{cases} x_1-2x_2+3x_3+17x_4 &= 4 \\ x_2-2x_3-13x_4 &= -5 & (L_2 \leftarrow -L_2) \\ x_2-3x_4 &= 3 \end{cases}$$

On fait disparaître le terme $x_2$ de la troisième ligne, puis on fait apparaître un coefficient $1$ pour le pivot de la position $(3,3)$ :
$$\begin{cases} x_1-2x_2+3x_3+17x_4 &= 4 \\ x_2-2x_3-13x_4 &= -5 \\ 2x_3+10x_4 &= 8 & (L_3 \leftarrow L_3-L_2) \end{cases} \qquad \begin{cases} x_1-2x_2+3x_3+17x_4 &= 4 \\ x_2-2x_3-13x_4 &= -5 \\ x_3+5x_4 &= 4 & (L_3 \leftarrow \tfrac12 L_3) \end{cases}$$

Le système est maintenant sous forme échelonnée.

**Partie B. Passage à une forme réduite.** Il reste à le mettre sous la forme échelonnée réduite. Pour cela, on ajoute à une ligne des multiples adéquats des lignes situées au-dessous d'elle, en allant du bas à droite vers le haut à gauche. On fait apparaître des $0$ sur la troisième colonne en utilisant le pivot de la troisième ligne :
$$\begin{cases} x_1-2x_2+3x_3+17x_4 &= 4 \\ x_2-3x_4 &= 3 & (L_2 \leftarrow L_2+2L_3) \\ x_3+5x_4 &= 4 \end{cases} \qquad \begin{cases} x_1-2x_2+2x_4 &= -8 & (L_1 \leftarrow L_1-3L_3) \\ x_2-3x_4 &= 3 \\ x_3+5x_4 &= 4 \end{cases}$$

On fait apparaître des $0$ sur la deuxième colonne (en utilisant le pivot de la deuxième ligne) :
$$\begin{cases} x_1-4x_4 &= -2 & (L_1 \leftarrow L_1+2L_2) \\ x_2-3x_4 &= 3 \\ x_3+5x_4 &= 4 \end{cases}$$

Le système est sous forme échelonnée réduite.

**Partie C. Solutions.** Le système est maintenant très simple à résoudre. En choisissant $x_4$ comme variable libre, on peut exprimer $x_1,x_2,x_3$ en fonction de $x_4$ :
$$x_1=4x_4-2, \quad x_2=3x_4+3, \quad x_3=-5x_4+4.$$
Ce qui permet d'obtenir toutes les solutions du système :
$$\mathcal{S}=\{(4x_4-2,\,3x_4+3,\,-5x_4+4,\,x_4) \mid x_4\in\mathbb{R}\}.$$

## Systèmes homogènes

Le fait que l'on puisse toujours se ramener à un système échelonné réduit implique le résultat suivant :

::: {.theorem}

Tout système homogène d'équations linéaires dont le nombre d'inconnues est strictement plus grand que le nombre d'équations a une infinité de solutions.

:::

::: {.example}

Considérons le système homogène
$$\begin{cases} 3x_1+3x_2-2x_3-x_5 &= 0 \\ -x_1-x_2+x_3+3x_4+x_5 &= 0 \\ 2x_1+2x_2-x_3+2x_4+2x_5 &= 0 \\ x_3+8x_4+4x_5 &= 0 \end{cases}$$

Sa forme échelonnée réduite est
$$\begin{cases} x_1+x_2+13x_5 &= 0 \\ x_3+20x_5 &= 0 \\ x_4-2x_5 &= 0 \end{cases}$$

On pose comme variables libres $x_2$ et $x_5$ pour avoir
$$x_1=-x_2-13x_5, \qquad x_3=-20x_5, \qquad x_4=2x_5,$$
et l'ensemble des solutions :
$$\mathcal{S}=\{(-x_2-13x_5,\,x_2,\,-20x_5,\,2x_5,\,x_5) \mid x_2,x_5\in\mathbb{R}\}$$
qui est bien infini.

:::

::: {.exercise}

1. Écrire un système linéaire à $4$ équations et $5$ inconnues qui soit échelonné mais pas réduit. Idem avec échelonné, non réduit, dont tous les coefficients sont $0$ ou $+1$. Idem avec échelonné et réduit.
2. Résoudre les systèmes échelonnés suivants :
$$\begin{cases} 2x_1-x_2+x_4 &= 1 \\ x_2+x_3-2x_4 &= 3 \\ 2x_3+x_4 &= 4 \\ x_4 &= -2 \end{cases} \quad \begin{cases} x_1+x_2+x_4 &= 0 \\ x_2+x_3 &= 0 \\ 2x_3+x_4 &= 0 \end{cases} \quad \begin{cases} x_1+2x_2+x_4 &= 0 \\ 2x_3-3x_4 &= 0 \end{cases}$$
3. Si l'on passe d'un système $(S)$ par une des trois opérations élémentaires à un système $(S')$, alors quelle opération permet de passer de $(S')$ à $(S)$ ?
4. Résoudre les systèmes linéaires suivants par la méthode du pivot de Gauss :
$$\begin{cases} 2x+y+z &= 3 \\ x-y+3z &= 8 \\ x+2y-z &= -3 \end{cases} \qquad \begin{cases} 2x_1+4x_2-6x_3-2x_4 &= 2 \\ 3x_1+6x_2-7x_3+4x_4 &= 2 \\ 5x_1+10x_2-11x_3+6x_4 &= 3 \end{cases}$$
5. Résoudre le système suivant, selon les valeurs de $a,b\in\mathbb{R}$ :
$$\begin{cases} x+y-z &= a \\ -x+2z &= b \\ 2y+2z &= 4 \end{cases}$$

:::

# Document en PDF {-}

[Chapitre 07 : Systèmes linéaires](PDF/mpsi-chap07.pdf)

## Navigation {-}

::: {.chap-nav}

[Chapitre 06 : Équations différentielles linéaires](mpsi-chap06.qmd){.prev}

[Menu MPSI](mpsi.qmd){.home}

[Chapitre 08 : Structures algébriques](mpsi-chap08.qmd){.next}

:::
