project:
  type: website
  output-dir: _site
  resources:
    - files/

website:
  title: "Mathématiques en CPGE"
  site-url: https://maharicpge.github.io/
  navbar:
    title: "Accueil"
    left:
      - href: cours/index.qmd
        text: Cours
      - href: td/index.qmd
        text: TD
      - href: annales/index.qmd
        text: Annales
      - href: tipe/index.qmd
        text: TIPE
      - conseils.qmd
      - contact.qmd
  page-footer: "© 2026 - Mathématiques en CPGE  ------------- Créateur : Saîd MAHARI (GSM: 0670050667)"

format:
  html:
    theme: [minty, custom.scss]
    css: styles.css
    toc: true
    include-after-body: analytics.html
