---
title: "MP — Annales"
pagetitle: "MP · Annales - Mathématiques en CPGE"
toc: false
format:
  html:
    css: styles.css
---


La préparation aux concours de la filière MP est un marathon qui exige rigueur, méthode et endurance. Au-delà de la simple assimilation du cours, la résolution des annales est une étape incontournable. Elle vous permettra de vous familiariser avec l'exigence des jurys, d'apprendre à gérer votre temps le jour J, et d'identifier les grands thèmes récurrents du programme (algèbre, analyse, probabilités...).

Vous trouverez ci-dessous l'ensemble des sujets de mathématiques du CNC tombés aux concours de 2011 à 2026. Pour en tirer le meilleur parti, nous vous conseillons de traiter ces épreuves en conditions réelles avant de vous référer aux corrigés. Ces derniers ont été pensés pour valoriser la clarté du plan, la rigueur des notations et la pertinence de la conclusion, autant de qualités essentielles pour faire la différence le jour du concours.


### Sujets et corrigés

| Année | Sujets | Corrigés |
| :---: | :--- | :--- |
| **2026** | **Math 1 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_649b7ca65f3f4a7aabd9f28152609b82.pdf)<br>**Math 2 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_a6e74678df5a41ac8f34265cff8ffec5.pdf) | **Math 1 :** *À venir*<br>**Math 2 :** *À venir* |
| **2025** | **Math 1 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_86ffc978d86d47ce9f8c1db228b409aa.pdf)<br>**Math 2 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_a867651a2fa24451893993993195c1e4.pdf) | **Math 1 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_2ff95521cbce49f4b40a28e05e377c14.pdf)<br>**Math 2 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_bc08b114e6984fa898e7f8362715585d.pdf) |
| **2024** | **Math 1 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_14b467aae7e44d29ac2c6693466e9b33.pdf)<br>**Math 2 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_aec8e873ec9b4f51b69f787760a148e7.pdf) | **Math 1 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_90000d11a44047bf9c116a98b85f9ed1.pdf)<br>**Math 2 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_1663552547db41298fbf5a5b401ac221.pdf) |
| **2023** | **Math 1 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_7d62cf8c07d5451ba7e032e6f1a158e7.pdf)<br>**Math 2 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_7355ffe194e1407d892e34fcab65eade.pdf) | **Math 1 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_d857c1e6d2224bc78918c98f9e05713e.pdf)<br>**Math 2 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_d5033ad8af414789be9bcde5623822f8.pdf) |
| **2022** | **Math 1 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_3a5b846eacc441c8a8e91089595f7364.pdf)<br>**Math 2 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_68b5bf3d949d425fa849b236f1efcb4e.pdf) | **Math 1 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_cfab7a545a15451f9ef0690f207a8e48.pdf)<br>**Math 2 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_56ad58c40a0c43e2afa8166e23231d61.pdf) |
| **2021** | **Math 1 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2021.pdf)<br>**Math 2 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2021.pdf) | **Math 1 :** *À venir*<br>**Math 2 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2021-corrige.pdf) |
| **2020** | **Math 1 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2020.pdf) | **Math 1 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2020-corrige.pdf) |
| **2019** | **Math 1 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2019.pdf)<br>**Math 2 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2019.pdf) | **Math 1 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2019-corrige.pdf)<br>**Math 2 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2019-corrige.pdf) |
| **2018** | **Math 1 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2018.pdf)<br>**Math 2 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2018.pdf) | **Math 1 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2018-corrige.pdf)<br>**Math 2 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2018-corrige.pdf) |
| **2017** | **Math 1 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2017.pdf)<br>**Math 2 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2017.pdf) | **Math 1 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2017-corrige.pdf)<br>**Math 2 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2017-corrige.pdf) |
| **2016** | **Math 1 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2016.pdf)<br>**Math 2 :** [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2016.pdf) | **Math 1 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-mp-2016-corrige.pdf)<br>**Math 2 :** [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-mp-2016-corrige.pdf) |
| **2015** | **Math 1 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_999158a514c345a78b12048e9033d8ea.pdf)<br>**Math 2 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_d9d8525ec3eb4d41b04825c606654aa1.pdf) | **Math 1 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_4d7e31006d534bde9597681f85ed6ded.pdf)<br>**Math 2 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_d5ac718cc7b44c18a5dfc27485fcbfc3.pdf) |
| **2014** | **Math 1 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_de39a5b958f64e12855d4a7513c8096a.pdf)<br>**Math 2 :** [Sujet](https://www.iamateacher.org/_files/ugd/99b3c9_0d6625cde48d448a9ed5ab5010350b06.pdf) | **Math 1 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_4525056e56f9490285360bd6c729b1ca.pdf)<br>**Math 2 :** [Corrigé](https://www.iamateacher.org/_files/ugd/99b3c9_b6b5f60cc3e94361bd7fad50ca3c0020.pdf) |
