---
title: "PSI — Annales"
pagetitle: "PSI · Annales - Mathématiques en CPGE"
toc: false
format:
  html:
    css: styles.css
---


La filière PSI forme des ingénieurs et des chercheurs dotés d'une solide culture mathématique, appliquée à la physique, à l'informatique et aux sciences de l'ingénieur. Dans ce contexte, les épreuves de mathématiques des concours exigent non seulement une maîtrise technique du programme, mais aussi une vraie capacité à modéliser des problèmes concrets et à rédiger des démonstrations rigoureuses.

Travailler les annales est donc un passage obligé de votre préparation. C'est en confrontant vos réponses aux attentes des jurys que vous affinerez votre style, gagnerez en efficacité, et apprendrez à reconnaître les classiques incontournables (algèbre linéaire, analyse asymptotique, probabilités discrètes...). Les corrigés proposés ici mettent l'accent sur la clarté du plan, la rigueur des notations et la pertinence de la conclusion : autant d'atouts qui font la différence le jour J.


### Sujets et corrigés

| Année | Sujets | Corrigés |
| :---: | :--- | :--- |
| 2026 | Math 1 : [Sujet](https://drive.google.com/file/d/1emroqzy885LamSsX8lGc7ZBNT3t-kBW5/view?usp=sharing) <br> Math 2 : [Sujet](https://drive.google.com/file/d/19Axlb0hRA0BEjb3rjg3Egzbvu59IP_wu/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/1c9t0aU9satMfkPOHZoo5IKcVXwr_H9a9/view?usp=drive_link) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/1xfJRHwJi1GR4ch6YiH27NHA50496Uniw/view?usp=drive_link) |
| 2025 | Math 1 : [Sujet](https://drive.google.com/file/d/10SY5e19npiFbboiDvbvrHk6hDhBfvhal/view?usp=drive_link) <br> Math 2 : [Sujet](https://drive.google.com/file/d/1MABQJtdbTKvX79Z4WPqU0dWCMELFFLRH/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/1ACe5mG9x0lFmoC_fcFVT_eu6DEy-wOZI/view?usp=drive_link) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/1Bjla13VMfC8SA2rbrFrPVAJw5sdel8EL/view?usp=drive_link) |
| 2024 | Math 1 : [Sujet](https://drive.google.com/file/d/1b1XSR-cegdOfFxgJEIQoanYY-eap6qr0/view?usp=drive_link) <br> Math 2 : [Sujet](https://drive.google.com/file/d/10i6lVMg5Lnlu0kOeqP3tuXQJaw-VLnTj/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/14D17dqggViSL6_yIr5C_vZn1WkVW-wMt/view?usp=sharing) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/1K6tsWeHZraYt7n0dlEVqi9AOJUamT4Q4/view?usp=drive_link) |
| 2023 | Math 1 : [Sujet](https://drive.google.com/file/d/19_Qn4CM2u2hRYA2ouIJidfTzCEHmC4zB/view?usp=drive_link) <br> Math 2 : [Sujet](https://drive.google.com/file/d/1DQ1UT2n0S40Q-sLlOuJmBWYiBPjNeuQV/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/1WG9-2Fr3UkOKc09xaV7jt1HYLO6XgZP9/view?usp=drive_link) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/17BxS-RB0SZU2J4kwTlHjKrBLdbNrL74E/view?usp=drive_link) |
| 2022 | Math 1 : [Sujet](https://drive.google.com/file/d/1zvpi-_f1X8LgYKtDAZ23zy-KDwLIhjXH/view?usp=drive_link) <br> Math 2 : [Sujet](https://drive.google.com/file/d/1nVmdpq_uIyMDy85fBVyz0tJ3HTQah3SN/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/14dWB1mx0Jg2xI9kw-Mi2ofNl7BvC-eDR/view?usp=drive_link) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/1BtjlVkQxEyaNXAeZOXPCwrRWpAUxVDMy/view?usp=sharing) |
| 2021 | Math 1 : [Sujet](https://drive.google.com/file/d/1jLgF7l09HhitHLlqmKETiXoH-HgqVKdE/view?usp=drive_link) <br> Math 2 : [Sujet](https://drive.google.com/file/d/1Zcbrq3xw7RpswfiCg8z9-yRJpHyQhypU/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/18lpDwUeW3JjwnSdTsvDEV8UxgW6AHPMP/view?usp=drive_link) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/1T3muymMc2cfteLI-W9NMJKViJ7Fuu4Wv/view?usp=drive_link) |
| 2020 | Sujet unique : [Sujet](https://drive.google.com/file/d/1yyDQcGHyesDmLNekzF8OHj7_H2WChbIJ/view?usp=drive_link) | Sujet unique : [Corrigé](https://drive.google.com/file/d/1XYiIlDF3cHNS7IzKAvvQceXd5wdexGlj/view?usp=drive_link) |
| 2019 | Math 1 : [Sujet](https://drive.google.com/file/d/1ghv9QqilTDSH_nE_qyWcYQtJ5DcJfmmi/view?usp=drive_link) <br> Math 2 : [Sujet](https://drive.google.com/file/d/1xkV5CFF-v9vvRxn5LWs9j1cPoenXCh9Z/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/1AbPAu_3rdPbYgf34lzpyC3Mfy2StFual/view?usp=drive_link) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/1DJ9gveOVrkeNQHWju5y8V1h5qu9EviN8/view?usp=drive_link) |
| 2018 | Math 1 : [Sujet](https://drive.google.com/file/d/1l0GQ3NUQrAbAK6Dqj5S7_f9G7R3BHmSz/view?usp=drive_link) <br> Math 2 : [Sujet](https://drive.google.com/file/d/1SCXA65g1aPnyMO7fGW9JHD_po-FHJGsF/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/1baN9R7dOaZTTj2HxtJ8teNuKeN2jGKfG/view?usp=drive_link) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/1cHQfo9zAaji22-sTvPT78bgXBzVp1Emp/view?usp=drive_link) |
| 2017 | Math 1 : [Sujet](https://drive.google.com/file/d/1H0aYTHoXLBQ5_SSgjdQZ45D5T1Gmcizt/view?usp=drive_link) <br> Math 2 : [Sujet](https://drive.google.com/file/d/1pfVW7Rm_Cujc6PLBxwdwFK_zC4pSew62/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/1gJKAwrUCDkUP1P7Pw2QwQR-JF-gj1ldh/view?usp=drive_link) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/1kGbdwoAL8v9nw65943HiYDwqRBuh3kUA/view?usp=drive_link) |
| 2016 | Math 1 : [Sujet](https://drive.google.com/file/d/16UiZFtnp0iQ0gyWuIpnt5yuYE20tipHp/view?usp=drive_link) <br> Math 2 : [Sujet](https://drive.google.com/file/d/1resBNo_W76usvv_WVRD3TTv6JpGyw20P/view?usp=drive_link) | Math 1 : [Corrigé](https://drive.google.com/file/d/1WuRtT6FbbANrEY7X-kgFFBvQcYg9j8AJ/view?usp=drive_link) <br> Math 2 : [Corrigé](https://drive.google.com/file/d/16LyB6faq4e-wPg4XbyTSMwiKASW6ovw0/view?usp=drive_link) |
| 2015 | Math 1 : [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-psi-2015.pdf) <br> Math 2 : [Sujet](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-psi-2015.pdf) | Math 1 : [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths1-psi-2015-corrige.pdf) <br> Math 2 : [Corrigé](https://groupe-reussite.fr/ressources/wp-content/uploads/Annales/concours-maroc/cnc/cnc-maths2-psi-2015-corrige.pdf) |
